server:
  port: 80

spring:
  servlet:
    multipart:
      max-file-size: 8Mb
      max-request-size: 10Mb
  #开发工具
  devtools:
    restart:
      #热部署生效 
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@192.168.2.75:1521:orcl 
    driverClassName: oracle.jdbc.OracleDriver
    username: summary
    password: summary
#  redis:
#    host: 192.168.2.71
#    port: 6379
#    timeout: 3000

#=============【log】====================
logging:
  config: classpath:logback/logback-spring-dev-colorful.xml
  level:
    com.supwisdom: debug 


#=============【mybatis】====================
mybatis-plus:
  #配置
  configuration:
    #二级缓存
    cache-enabled: false

#=============【系统变量】====================
app:
  page-constant:
    login-title: 登陆
    script-name: 图灵屋
  #配置
  config: 
    # 接口文档参数
    swagger2: 
      enable: true
      title: 接口文档
      desc: 接口文档描述
      basePackage: com.supwisdom
      serverUrl: http://localhost:8080
    # 缓存配置变量
    cache:
      # 当前使用的缓存组件
      use: ehcache
      ehcache:
        maxElementsInMemory: 5000
        overflowToDisk: false
        eternal: false
        timeToLiveSeconds: 0
        timeToIdleSeconds: 600
    # 定时器配置
    timer:
      threadPoolSize: 8
      threadPrefix: ScheduleTask-
    # shiro权限认证
    shiro:
      loginUrl: /login
      successUrl: bbb
      authenTimeout: 1800000
      
      
    

